mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shi.urls')),
]

shi/urls.py
from django.urls import path

from . import views

app_name = 'shi'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:input_id>/select/', views.select, name='select'),
    path('<int:input_id>/make/', views.make, name='make'),
    path('draft/', views.draft, name='draft'),
    path('<int:input_id>/publish/', views.publish, name='publish'),
]

shi/models.py
from django.db import models
from django.utils import timezone


class Shi(models.Model):
    input_text = models.CharField(max_length=200)
    output_text = models.TextField(blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.input_text


class Choice(models.Model):
    input = models.ForeignKey(Shi, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

shi/forms.py
from django import forms

from .models import Shi, Choice


class ShiForm(forms.ModelForm):

    class Meta:
        model = Shi
        fields = ('input_text',)

shi/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Shi, Choice
from .forms import ShiForm
from .quence import Quence


class IndexView(generic.ListView):
    template_name = 'shi/index.html'
    context_object_name = 'latest_shi_list'

    def get_queryset(self):
        """Return the last five published shis."""
        return Shi.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') #[:5]


class DetailView(generic.DetailView):
    model = Shi
    context_object_name = 'shi'
    template_name = 'shi/detail.html'


def quence(shi, text):
    q = Quence()
    output = q.call_tf(text)
    for out in output:
        choice = Choice()
        choice.input = shi
        choice.choice_text = out
        choice.save()


def new(request):
    if request.method == "POST":
        form = ShiForm(request.POST)
        if form.is_valid():
            shi = form.save(commit=False)
            shi.save()
            quence(shi, shi.input_text)
            return redirect('shi:detail', pk=shi.pk)
    else:
        form = ShiForm()
    return render(request, 'shi/new.html', {'form': form})


def select(request, input_id):
    shi = get_object_or_404(Shi, pk=input_id)
    try:
        selected_choice = shi.choice_set.get(pk=request.POST['choice'])
        shi.choice_set.exclude(pk=request.POST['choice']).delete()
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the voting form.
        return render(request, 'shi/detail.html', {
            'shi': shi,
            'error_message': "You didn't select a choice.",
        })
    else:
        output_text = shi.output_text
        output_text += selected_choice.choice_text + '\n'
        shi.output_text = output_text
        shi.save()
        return render(request, 'shi/detail.html', {'shi': shi,})


def make(request, input_id):
    shi = get_object_or_404(Shi, pk=input_id)
    choice = shi.choice_set.get()
    choice_text = choice.choice_text
    shi.choice_set.all().delete()
    quence(shi, choice_text)
    return render(request, 'shi/detail.html', {'shi': shi,})


def draft(request):
    shi = Shi.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'shi/draft.html', {'shi': shi,})


def publish(request, input_id):
    shi = get_object_or_404(Shi, pk=input_id)
    shi.publish()
    shi.choice_set.all().delete()
    return redirect('shi:detail', pk=shi.pk)

shi/templates/shi/base.html
{% load static %}
<html>
    <head>
        <title>Quence</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'shi/shi.css' %}" />
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'shi:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'shi:draft' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <h1><a href="{% url 'shi:index' %}">Quence</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

shi/templates/shi/detail.html
{% extends 'shi/base.html' %}

{% block content %}
<div class="shi">
    <h1>{{ shi.input_text }}</h1>
    <p>{{ shi.output_text|linebreaksbr }}</p>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'shi:select' shi.id %}" method="post" onsubmit="select.disabled=true;">
        {% csrf_token %}
        {% if shi.choice_set.count == 3 %}
            {% for choice in shi.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
            {% endfor %}
            <input type="submit" value="선택" name="select"/>
        {% else %}
            {% if shi.published_date %}
                <div class="date">
                    {{ shi.published_date }}
                </div>
                {% else %}
                    <a class="btn btn-default" href="{% url 'shi:make' shi.id %}"
                       onclick="style.display='none';">만들기</a>
                    <a class="btn btn-default" href="{% url 'shi:publish' shi.id %}">출판하기</a>
                {% endif %}
        {% endif %}
    </form>
</div>
{% endblock %}

shi/templates/shi/draft.html
{% extends 'shi/base.html' %}

{% block content %}
    {% for shi in shi %}
        <div class="shi">
            <p class="date">created: {{ shi.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'shi:detail' shi.id %}">{{ shi.input_text }}</a></h1>
            <p>{{ shi.output_text|truncatechars:200|linebreaksbr }}</p>
        </div>
    {% empty %}
        <p>아직 쓰여진 시가 없습니다. :(</p>
    {% endfor %}
{% endblock %}

shi/templates/shi/index.html
{% extends 'shi/base.html' %}

{% block content %}
    {% if latest_shi_list %}
        {% for shi in latest_shi_list %}
            <div class="shi">
                <div class="date">
                    {{ shi.published_date }}
                </div>
                <h1><a href="{% url 'shi:detail' shi.id %}">{{ shi.input_text }}</a></h1>
                <p>{{ shi.output_text|linebreaksbr }}</p>
            </div>
        {% endfor %}
    {% else %}
    <p>발행된 시가 없습니다.</p>
    {% endif %}
{% endblock %}

shi/templates/shi/new.html
{% extends 'shi/base.html' %}

{% block content %}
    <h1>Quence와 함께 시 쓰기</h1>
    <form method="POST" class="shi-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default"
                onclick="this.disabled=true;">한 줄 쓰기</button>
    </form>
{% endblock %}